url: http://entenhausen.freifunk.net

community:
  # Metadata
  name: "Entenhausen"

  # Custom URLs
  url_wiki:  "/wiki"
  url_geomap: "/map/geomap.html"
  url_graph: "/map/graph.html"
  url_nodelist: "/wiki/Knoten"
  url_mailman: "http://lists.entenhausen.freifunk.net/mailman/listinfo/list"

  # Mail Contacts
  mail_info: "info@entenhausen.freifunk.net"
  mail_keys: "keys@entenhausen.freifunk.net"
  mail_discussion: "discussion@entenhausen.freifunk.net"

  # Other Contacts
  sip: ["space@sip.ffeh", "space@10.254.254.254"] # Optional
  twitter: "FreifunkEntenhausen" # Optional
  irc: "#ffeh"

  # GPS
  geo_lat: 53.869722
  geo_lon: 10.686389

firmware:
  base: "http://luebeck.freifunk.net/firmware/stable/"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/freifunk-entenhausen/site-ffeh"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"
