url: http://freifunk.in-kiel.de/

community:
  # Metadata
  name: "Kiel"

  # Custom URLs
  url_wiki:  "/wiki"
  url_geomap: "/ffmap/geomap.html"
  url_graph: "/ffmap/graph.html"
  url_nodelist: "/ffmap/list.html"
  url_mailman: "http://toppoint.de/cgi-bin/mailman/listinfo/freifunk"

  # Mail Contacts
  mail_info: "freifunk@in-kiel.de"
  mail_keys: "freifunk@in-kiel.de"
  mail_discussion: "freifunk@in-kiel.de"

  # Other Contacts
  #sip: ["space@sip.ffeh", "space@10.254.254.254"] # Optional
  #twitter: "FreifunkEntenhausen" # Optional
  irc: "#ffki"

  # GPS
  geo_lat: 54.3216753
  geo_lon: 10.1371858

firmware:
  base: "http://freifunk.in-kiel.de/firmware/stable/"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/sargon/site-ffki"
  # Path to local checkout of the site repo
  gluon_site_dir: "/opt/site-ffki/"
