url: http://freifunk.localhost/

community:
  # Metadata
  name: "Nord"
  meta: "Freifunk Nord"
  country: "DE"

  # Custom URLs
  url_wiki:  "http://wiki.freifunk.in-kiel.de/"

  url_geomap: "http://map.freifunk.in-kiel.de/"
  url_graph: "http://graph.freifunk.in-kiel.de/"
  url_nodelist: "http://alfred.freifunk.in-kiel.de/"

  url_mailman: "http://lists.freifunk.net/mailman/listinfo/ffnord-freifunk.net"

  url_firmware: "http://freifunk.in-kiel.de/firmware.html"

  url_blog_cms: "https://github.com/ffnord/ffki-blog"

  # Mail Contacts
  mail_info: "freifunk@in-kiel.de"
  mail_keys: "freifunk-keys@in-kiel.de"
  mail_discussion: "freifunk@in-kiel.de"

  # Other Contacts
  #sip: ["space@sip.ffki"] # Optional
  twitter: "ff_Kiel" # Optional
  irc: "ffnord"

  # GPS
  geo_lat: 54.0
  geo_lon: 10.0

firmware:
  #base: "https://freifunk.in-kiel.de/firmware/stable/"
  base: "http://localhost/freifunk/firmware/ffki/0.7.1/"
  #base: "http://gluon.ffki.de/firmware/stable/"
  #base: "http://freifunk.discovibration.de/firmware/firmware-0.7.1/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/ffnord/site-ffnord/"

  # Path to local checkout of the site repo
  gluon_site_dir: "/opt/site-ffnord/"

tld:
  label: "ffnord"
  ns:
    - "10.116.168.1"
    - "fda1:384a:74de:4242::2"
